name: Build_And_Test

on:
  push:
    branches: [ dev, master, 'feat/**' ]
  pull_request:
    branches: [ dev, master ]

jobs:

  linux:    
    name: build on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x 
    
    - name: Show dotnet Version
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes

    - name: Build with dotnet      
      run: |
        dotnet build rdb-tools.sln

#    - name: Run tests on net6.0
#      run: |
#        dotnet test tests/RDBParserTests/RDBParserTests.csproj