name: Release_NUGET_Unstable

on:
    push:
      tags:
        - "*.*.*-beta*"
        - "*.*.*-rc*"

jobs:
  publish_nuget:    
    name: Build and upload nuget artifact
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Build with dotnet
      run: |
        dotnet build --configuration Release --source https://api.nuget.org/v3/index.json img-go.sln      
    - name: Pack with dotnet
      run: |
        ver=alpha`date +%Y%m%d%H%M%S`
        dotnet pack src/ImgGoCli/ImgGoCli.csproj --version-suffix $ver -o /home/runner/work/nugetpkgs -c Release --no-build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: nugetpkgs
        path: /home/runner/work/nugetpkgs  

  release_nuget:
      name: Release to Nuget
      needs: publish_nuget
      runs-on: ubuntu-latest
  
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v1
          with:
            name: nugetpkgs
        - name: list nugetpkgs
          run: ls nugetpkgs
        - name: Release
          run: |
            for file in nugetpkgs/*.nupkg
            do
              dotnet nuget push $file -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://www.nuget.org/api/v2/package
            done
